head	1.2;
access;
symbols
	REL_1_5_4:1.1.1.1
	initial:1.1.1.1
	e-s:1.1.1;
locks; strict;
comment	@ * @;


1.2
date	2001.04.14.22.37.30;	author bastiaan;	state dead;
branches;
next	1.1;

1.1
date	2000.10.05.18.37.28;	author e-s;	state Exp;
branches
	1.1.1.1;
next	;

1.1.1.1
date	2000.10.05.18.37.28;	author e-s;	state Exp;
branches;
next	;


desc
@@


1.2
log
@Moved public header files from cppunit dir to include/cppunit, to separate them from internal header files like estring.h.
@
text
@#ifndef CPPUNIT_TESTFAILURE_H
#define CPPUNIT_TESTFAILURE_H

#include <string>

namespace CppUnit {

  class Test;
  class Exception;


  /**
   * A TestFailure collects a failed test together with
   * the caught exception.
   *
   * TestFailure assumes lifetime control for any exception
   * passed to it.  The lifetime of tests is handled by
   * their TestSuite (if they have been added to one) or
   * whomever creates them.
   * 
   * see TestResult
   * see TestSuite
   *
   */
  class TestFailure 
  {
    public:
      TestFailure (Test *failedTest, Exception *thrownException);
      ~TestFailure ();

      Test*        failedTest ();

      Exception*   thrownException ();

      std::string  toString () const;

    protected:
      Test         *m_failedTest;
      Exception    *m_thrownException;

    private: 
      TestFailure (const TestFailure& other); 
      TestFailure& operator= (const TestFailure& other); 
  };

  /// Gets the failed test.
  inline Test *TestFailure::failedTest ()
  { return m_failedTest; }


  /// Gets the thrown exception.
  inline Exception *TestFailure::thrownException ()
  { return m_thrownException; }

} // namespace CppUnit

#endif // CPPUNIT_TESTFAILURE_H
@


1.1
log
@Initial revision
@
text
@@


1.1.1.1
log
@initial check in.
@
text
@@
